import Database from 'better-sqlite3'

export type ManifestContext = {
  name: string
  market: string
  propertyType: string
  quarter: string
  lastUpdated: string
}

export type DataSummary = {
  marketStatRows: number
  submarketStatRows: number
  propertyCount: number
  leaseCount: number
  availabilityRatePct: number | null
  avgAskingRate: number | null
  currentQuarterNetAbsorption: number | null
  underConstructionSf: number | null
  topSubmarkets: string[]
}

export function computeDataSummary(
  db: Database.Database,
  quarter: string
): DataSummary {
  const marketRows = db
    .prepare(
      `SELECT COUNT(*) AS n FROM market_statistic WHERE quarter = ?`
    )
    .get(quarter) as { n: number }

  const submarketRows = db
    .prepare(
      `SELECT COUNT(*) AS n FROM submarket_statistic WHERE quarter = ?`
    )
    .get(quarter) as { n: number }

  const propertyCount = (
    db.prepare('SELECT COUNT(*) AS n FROM property').get() as { n: number }
  ).n
  const leaseCount = (
    db.prepare('SELECT COUNT(*) AS n FROM lease').get() as { n: number }
  ).n

  const headlineRow = db
    .prepare(
      `SELECT
        AVG(total_availability_pct) AS availability,
        AVG(avg_direct_asking_rate_dollars_sf) AS asking_rate,
        SUM(current_quarter_net_absorption_sf) AS qtr_absorption,
        SUM(under_construction_sf) AS under_construction
      FROM market_statistic
      WHERE quarter = ?`
    )
    .get(quarter) as {
    availability: number | null
    asking_rate: number | null
    qtr_absorption: number | null
    under_construction: number | null
  }

  const topSubmarketRows = db
    .prepare(
      `SELECT submarket
         FROM submarket_statistic
        WHERE quarter = ?
        ORDER BY net_rentable_area_msf DESC
        LIMIT 5`
    )
    .all(quarter) as { submarket: string }[]

  return {
    marketStatRows: marketRows.n,
    submarketStatRows: submarketRows.n,
    propertyCount,
    leaseCount,
    availabilityRatePct: headlineRow.availability,
    avgAskingRate: headlineRow.asking_rate,
    currentQuarterNetAbsorption: headlineRow.qtr_absorption,
    underConstructionSf: headlineRow.under_construction,
    topSubmarkets: topSubmarketRows.map((r) => r.submarket)
  }
}

function formatPct(value: number | null): string {
  if (value === null) return '_not yet imported_'
  return `${value.toFixed(1)}%`
}

function formatRate(value: number | null): string {
  if (value === null) return '_not yet imported_'
  return `$${value.toFixed(2)}/SF FSG/yr`
}

function formatSf(value: number | null): string {
  if (value === null) return '_not yet imported_'
  if (value < 0) return `(${Math.abs(value).toLocaleString('en-US')}) SF`
  return `${value.toLocaleString('en-US')} SF`
}

function renderDataSummary(summary: DataSummary): string {
  if (
    summary.marketStatRows === 0 &&
    summary.submarketStatRows === 0 &&
    summary.propertyCount === 0 &&
    summary.leaseCount === 0
  ) {
    return '_No data has been imported yet._'
  }

  const top =
    summary.topSubmarkets.length > 0
      ? summary.topSubmarkets.join(', ')
      : '_no submarket data_'

  return [
    `- Market statistic rows: ${summary.marketStatRows}`,
    `- Submarket statistic rows: ${summary.submarketStatRows}`,
    `- Properties: ${summary.propertyCount}`,
    `- Leases: ${summary.leaseCount}`,
    `- Availability Rate (avg across classes): ${formatPct(summary.availabilityRatePct)}`,
    `- Avg Asking Rate: ${formatRate(summary.avgAskingRate)}`,
    `- Current Quarter Net Absorption: ${formatSf(summary.currentQuarterNetAbsorption)}`,
    `- Under Construction: ${formatSf(summary.underConstructionSf)}`,
    `- Key Submarkets: ${top}`
  ].join('\n')
}

export function renderWorkspaceManifest(
  ctx: ManifestContext,
  summary?: DataSummary
): string {
  const summaryBlock = summary
    ? renderDataSummary(summary)
    : '_Auto-generated by the app on save. No data has been imported yet._'

  return `# Quarterline Workspace

## Context

- **Workspace**: ${ctx.name}
- **Market**: ${ctx.market}
- **Quarter**: ${ctx.quarter}
- **Property Type**: ${ctx.propertyType}
- **Last Updated**: ${ctx.lastUpdated}

## What You Can Do

You are an AI assistant helping a commercial real estate research analyst
assemble a quarterly market report.

### Read (for context)

- \`data/market-statistics.json\` — market-level statistics by property class.
- \`data/submarket-statistics.json\` — submarket-level statistics.
- \`data/property-data.json\` — property and asset details.
- \`data/lease-data.json\` — lease records with tenant, SF, terms.
- \`data/financial-metrics.json\` — NOI, cap rates, asking rents, absorption.
- \`data/scenario-results.json\` — what-if scenario outputs.
- \`notes/*.md\` — analyst notes and observations.
- \`narratives/*.md\` — existing report section drafts.

### Write (to generate content)

- \`narratives/*.md\` — write or update report section narratives.
- \`notes/*.md\` — add analysis notes.

Use the section naming convention below when creating new narrative files.

### Do Not Touch

- \`workspace.db\` — SQLite database, managed by the app.
- \`sources/*\` — confidential source documents.
- \`exports/*\` — generated report files.
- \`.quarterline/*\` — app configuration.
- \`WORKSPACE.md\` — this file (app-managed).

## Report Structure

The quarterly report follows this section order. Each section corresponds to
a narrative file in \`narratives/\`:

1. \`market-overview.md\` — headline market narrative.
2. \`availability.md\` — availability trends and analysis.
3. \`asking-rent.md\` — rent trends by class and submarket.
4. \`net-absorption.md\` — absorption patterns and drivers.
5. \`construction-activity.md\` — pipeline and deliveries.
6. \`leasing-activity.md\` — leasing volume, key transactions.
7. \`custom/<name>.md\` — additional analyst-defined sections.

## Writing Guidelines

- Write as a CRE research analyst, not as an AI assistant.
- Be specific: cite numbers from the data files.
- Use the market and quarter from the Context section above.
- Refer to submarkets, property classes, and tenants by name.
- Keep narratives to 2-3 paragraphs per section.
- Do not fabricate data. If a data point is not in the data files, do not
  invent it.
- Use parentheses for negative numbers: (443,000) not -443,000.
- Use SF for square feet, MSF for millions of square feet, $/SF for per
  square foot rates.

## Current Data Summary

${summaryBlock}
`
}
