export type ManifestContext = {
  name: string
  market: string
  propertyType: string
  quarter: string
  lastUpdated: string
}

export function renderWorkspaceManifest(ctx: ManifestContext): string {
  return `# Quarterline Workspace

## Context

- **Workspace**: ${ctx.name}
- **Market**: ${ctx.market}
- **Quarter**: ${ctx.quarter}
- **Property Type**: ${ctx.propertyType}
- **Last Updated**: ${ctx.lastUpdated}

## What You Can Do

You are an AI assistant helping a commercial real estate research analyst
assemble a quarterly market report.

### Read (for context)

- \`data/market-statistics.json\` — market-level statistics by property class.
- \`data/submarket-statistics.json\` — submarket-level statistics.
- \`data/property-data.json\` — property and asset details.
- \`data/lease-data.json\` — lease records with tenant, SF, terms.
- \`data/financial-metrics.json\` — NOI, cap rates, asking rents, absorption.
- \`data/scenario-results.json\` — what-if scenario outputs.
- \`notes/*.md\` — analyst notes and observations.
- \`narratives/*.md\` — existing report section drafts.

### Write (to generate content)

- \`narratives/*.md\` — write or update report section narratives.
- \`notes/*.md\` — add analysis notes.

Use the section naming convention below when creating new narrative files.

### Do Not Touch

- \`workspace.db\` — SQLite database, managed by the app.
- \`sources/*\` — confidential source documents.
- \`exports/*\` — generated report files.
- \`.quarterline/*\` — app configuration.
- \`WORKSPACE.md\` — this file (app-managed).

## Report Structure

The quarterly report follows this section order. Each section corresponds to
a narrative file in \`narratives/\`:

1. \`market-overview.md\` — headline market narrative.
2. \`availability.md\` — availability trends and analysis.
3. \`asking-rent.md\` — rent trends by class and submarket.
4. \`net-absorption.md\` — absorption patterns and drivers.
5. \`construction-activity.md\` — pipeline and deliveries.
6. \`leasing-activity.md\` — leasing volume, key transactions.
7. \`custom/<name>.md\` — additional analyst-defined sections.

## Writing Guidelines

- Write as a CRE research analyst, not as an AI assistant.
- Be specific: cite numbers from the data files.
- Use the market and quarter from the Context section above.
- Refer to submarkets, property classes, and tenants by name.
- Keep narratives to 2-3 paragraphs per section.
- Do not fabricate data. If a data point is not in the data files, do not
  invent it.
- Use parentheses for negative numbers: (443,000) not -443,000.
- Use SF for square feet, MSF for millions of square feet, $/SF for per
  square foot rates.

## Current Data Summary

_Auto-generated by the app on save. No data has been imported yet._
`
}
